### ISSUE TITLE
install_referrer intents removed on March 1, 2020

### ISSUE THREAD

**Issue by justjoeyuk** [boundstate/capacitor-branch-deep-links#6]
I received the following information from Branch via Email and I'm wondering if any action will be needed for this plugin. Is there any action that needs to be taken on this end?

### Message

A couple of months ago, Google announced that they will stop broadcasting install_referrer intents on March 1, 2020. Branch uses this data to help power our deep linking and attribution services on Android devices.

Fortunately, Google has also introduced the Play Install Referrer API to provide the same data. This API provides better performance, and there is a good chance it is already configured in your app. However, Google has recently contacted several Branch customers about this, so we wanted to proactively reach out and help you confirm your configuration in advance of the cutoff date. 

**REQUIRED ACTIONS**

Branch Android SDK: please do EITHER of the following for your Android app:

1. Ensure you've linked the Play Install Referrer Library as a Gradle dependency. To do this, please add this directive to your build.gradle file (it is not necessary to implement any of the other steps on this page, as the Branch SDK will handle the rest for you). 

OR

2. Update to the most recent version of the SDK (v4.3.2), which bundles the Play Install Referrer Library automatically.

TUNE Android SDK: Please update to the most recent version of the SDK (v6.1.2, currently only available on JCenter). The TUNE Android SDK already bundles the Play Install Referrer Library, but older versions contain a rare bug that can cause a background thread to pause for up to 60 seconds while waiting for install_referrer data to be returned.

In addition, we recommend confirming that the following entry has been removed from your AndroidManifest.xml file:

Branch SDK

```
<receiver android:name="io.branch.referral.InstallListener" android:exported="true">
   <intent-filter>
   <action android:name="com.android.vending.INSTALL_REFERRER" />
   </intent-filter>
</receiver>
```

TUNE SDK

```
<receiver android:name="com.tune.TuneTracker">
    <intent-filter>
    <action android:name="com.android.vending.INSTALL_REFERRER" />
    </intent-filter>
</receiver>
```

If you have any questions, please feel free to reach out to support@branch.io.

Sincerely,

The Branch Team

**Comment by mikejpeters** [comment]
Thanks for the heads up! 

This plugin currently uses the Branch SDK v3, so based on this email, users of this plugin should add the Play Install Referrer Library as a Gradle dependency.

I'll update the README to include the necessary change (until some point in the future where I hopefully have time to update this plugin to use the SDK v4 which has it bundled).

**Comment by tafelnl** [comment]
As of https://github.com/BranchMetrics/capacitor-branch-deep-links/commit/4c24eb00af44a4b16e88062296d9fbb21ea92f60 install_referrer should not be included anymore. As a matter of fact, I think the whole config should be changed. See: https://github.com/BranchMetrics/capacitor-branch-deep-links/issues/21
