### ISSUE TITLE
Update docs with info on the URI Scheme employed

### ISSUE THREAD

**Issue by Taylorsuk** [boundstate/capacitor-branch-deep-links#7]
Thanks so much for this plugin! It's really going to help me out. 

I'm confused about what I am going to be putting into the **Android URI Scheme** and **iOS URI Scheme** input boxes when using the Capacitor plugin as opposed to the Cordova one? 

See image below:
<img width="1053" alt="Screenshot 2020-03-17 at 14 43 11" src="https://user-images.githubusercontent.com/852767/76867847-ff23b980-685d-11ea-9893-1ab3e551717c.png">

This screen is found in the [Branch Dashboard](https://dashboard.branch.io/link-settings/general)

**Comment by mikejpeters** [comment]
The URI schemes are defined by you, and should ideally be unique to your app.

This project is meant to ease the integration of Branch.io with Capacitor, but can't be a substitute for understanding how deep linking on Android and iOS work. It's still necessary to read the Android and iOS docs, as well as the Branch.io docs.

Here are a couple resources to get you started:

* https://branch.io/what-is-deep-linking/
* https://branch.io/glossary/uri-schemes/
* https://help.branch.io/using-branch/docs/default-link-behavior
